// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-campaigns.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_campaigns_default = defineTool({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List campaigns visible to the signed-in user, ordered by display_order.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max campaigns to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("campaigns").select("id, code, title, description, campaign_type, display_order, created_at").order("display_order", { ascending: true }).limit(limit ?? 50);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-campaign.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_campaign_default = defineTool2({
  name: "get_campaign",
  title: "Get campaign",
  description: "Fetch a single campaign by its short code (e.g. 'ice-takedown') along with its events/actions.",
  inputSchema: {
    code: z2.string().trim().min(1).describe("Campaign short code / slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser2(ctx);
    const { data: campaign, error } = await supabase.from("campaigns").select("*").eq("code", code).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!campaign)
      return { content: [{ type: "text", text: `No campaign with code '${code}'` }], isError: true };
    const { data: eoas } = await supabase.from("events_actions").select("id, utm_id, type, mobilize_code, title, city, state, zip_code, assigned_deck_slug").eq("campaign_id", campaign.id).order("created_at", { ascending: true });
    const payload = { campaign, events_actions: eoas ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-campaign-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_campaign_stats_default = defineTool3({
  name: "get_campaign_stats",
  title: "Get campaign stats",
  description: "Get aggregated viral tracking stats (tokens, views, shares by level) for one or more campaign codes.",
  inputSchema: {
    codes: z3.array(z3.string().trim().min(1)).min(1).max(20).describe("List of campaign short codes to aggregate.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ codes }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).rpc("get_campaign_stats", {
      campaign_codes: codes
    });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { stats: data }
    };
  }
});

// src/lib/mcp/tools/list-decks.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_decks_default = defineTool4({
  name: "list_decks",
  title: "List decks",
  description: "List all slide decks (slug + display order) visible to the signed-in user.",
  inputSchema: {
    limit: z4.number().int().min(1).max(500).optional().describe("Max decks to return (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser4(ctx).from("decks").select("slug, display_order").order("display_order", { ascending: true }).limit(limit ?? 100);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { decks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/recent-events.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_events_default = defineTool5({
  name: "list_recent_events",
  title: "List recent tracking events",
  description: "Return the most recent url_events (scans/views/shares) with geo info. Optionally filter by event_type.",
  inputSchema: {
    limit: z5.number().int().min(1).max(200).optional().describe("Max events (default 50)."),
    event_type: z5.enum(["scan", "view", "share"]).optional().describe("Optional filter by event type.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, event_type }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser5(ctx).from("url_events").select("id, token, event_type, occurred_at, city, region, country_code, zip_code, location_source").is("deleted_at", null).order("occurred_at", { ascending: false }).limit(limit ?? 50);
    if (event_type) query = query.eq("event_type", event_type);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wznilzguqjwvkysuleta";
var mcp_default = defineMcp({
  name: "democracy-forge-mcp",
  title: "Democracy Forge",
  version: "0.1.0",
  instructions: "Read-only access to Democracy Forge campaigns, decks, and viral tracking events. Use list_campaigns to discover campaigns, get_campaign for details on one campaign, get_campaign_stats for aggregated viral metrics, list_decks for slide decks, and list_recent_events for the newest scan/view/share activity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_campaigns_default, get_campaign_default, get_campaign_stats_default, list_decks_default, recent_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
