-- Add is_simulated column to tokens table
ALTER TABLE public.tokens
ADD COLUMN is_simulated BOOLEAN NOT NULL DEFAULT false;

-- Add is_simulated column to url_events table
ALTER TABLE public.url_events
ADD COLUMN is_simulated BOOLEAN NOT NULL DEFAULT false;

-- Add indexes for filtering
CREATE INDEX idx_tokens_is_simulated ON public.tokens(is_simulated);
CREATE INDEX idx_url_events_is_simulated ON public.url_events(is_simulated);

-- Add comments
COMMENT ON COLUMN public.tokens.is_simulated IS 'Marks tokens generated by the simulator for testing purposes';
COMMENT ON COLUMN public.url_events.is_simulated IS 'Marks events generated by the simulator for testing purposes';